spring:
 application:
  name: apigateway

server:
 port: 8700

zuul:
 ignoredServices: '*'
 sensitive-headers:
 routes:
  customer:
   path: /api/v1/customer/**
   serviceId: client01
   strip-prefix: true

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8500/eureka/
  instance:
   prefer-ip-address: true

ribbon:
 ConnectTimeout: 5000
 ReadTimeout: 2000

management:
 endpoints:
  web:
   exposure:
    include: "*"
